local:
  hosts:
    192.168.215.135:
      domain: test.grafikart.fr
      root_path: "/home/{{ ansible_user }}/test.grafikart.fr"
      self_signed: yes
      database: grafikart
      database_password: dotted-statue-hurt
      typesense_key: P8SSmEw4gvSe3gdQXyyQW87FYr4AKRf5Sxk5nrXGyGk
      ansible_user: debian
remote:
  hosts:
    212.47.227.114:
      domain: beta.grafikart.fr
      root_path: "/home/{{ ansible_user }}/beta.grafikart.fr"
      self_signed: no
      database: grafikart
      database_password: dotted-statue-hurt
      typesense_key: P8SSmEw4gvSe3gdQXyyQW87FYr4AKRf5Sxk5nrXGyGk
      ansible_user: debian
      ansible_python_interpreter: /usr/bin/python3
