all:
  hosts:
    192.168.215.135:
      domain: test.grafikart.fr
      root_path: "/home/{{ ansible_user }}/test.grafikart.fr"
      self_signed: yes
      database: grafikart
      database_password: dotted-statue-hurt
      typesense_key: P8SSmEw4gvSe3gdQXyyQW87FYr4AKRf5Sxk5nrXGyGk
