---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Installation du serveur
  hosts: all
  remote_user: debian

  pre_tasks:
    - name: "APT | Update & Upgrade"
      become: true
      apt:
        upgrade: dist
        update_cache: yes

  roles:
    - {role: tools, tags: tools, become: true}
    - {role: firewall, become: true, tags: firewall}
    - {role: php, become: true, tags: php}
    - {role: nginx, become: true, tags: nginx}
    - {role: pgsql, become: true, tags: pgsql}
