language: node_js
node_js:
  - 14
services:
  - docker
install:
  - make install
script:
  - make lint
  - make test
cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.cache/yarn
    - $HOME/.composer/cache/files
