version: '3.1'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    restart: unless-stopped
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis
      TYPESENSE_KEY: typesensekey
      TYPESENSE_HOST: typesense:8108
      MAIL_DSN: sendmail://default
      MAILER_URL: postgresql://grafikart:grafikart@db:5432/grafikart?serverVersion=12&chartset=utf8
      MERCURE_PUBLISH_URL: http://mercure/.well-known/mercure
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: grafikart
      POSTGRES_USER: grafikart
      POSTGRES_DB: grafikart
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./var:/var/www/var
  redis:
    restart: unless-stopped
    image: redis:6-alpine
  typesense:
    restart: unless-stopped
    image: typesense/typesense:0.16.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    volumes:
      - search-data:/data
    ports:
      - 8108:8108
  mercure:
    restart: unless-stopped
    image: dunglas/mercure
    environment:
      JWT_KEY: mercure_subscriber
      PUBLISHER_JWT_KEY: mercure_publisher
      ALLOW_ANONYMOUS: 0
    ports:
      - 8001:80
  messenger:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    restart: unless-stopped
    command: ['php', 'bin/console', 'messenger:consume', 'async', '--limit=10', '-vv']
    environment:
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed

volumes:
  db-data:
    driver: local
  search-data:
    driver: local
