version: '3.9'
services:
  php:
    environment:
      PHP_IDE_CONFIG: serverName=grafikart
      APP_ENV: dev
  db:
    ports:
      - 5432:5432 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
  mercure:
    environment:
      CORS_ALLOWED_ORIGINS: 'http://grafikart.localhost:8000'
  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  node:
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./tools/docker/node
    command: yarn run dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

