---
- name: Outils | Timezone
  community.general.timezone:
    name: Europe/Paris
- name: Outils | Locale française
  community.general.locale_gen:
    name: fr_FR.UTF-8
    state: present
- name: Outils | Install
  apt:
    name:
      - redis
      - fish
      - vim
      - git
      - ntp
      - rsync
    state: present
- name: Outils | création de ~/.vim/autoload
  file: state=directory path=~/.vim/autoload
  become: no
- name: Outils | Téléchargement plug.vim
  become: no
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
- name: Outils | Téléchargement .vimrc
  become: no
  get_url:
    url: https://raw.githubusercontent.com/Grafikart/dotfiles/master/config/vim/.vimrc
    dest: ~/.vimrc
- name: Outils | Passage sur fish
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
